### ISSUE TITLE
Any plan to merge outstanding existing pull request before starting yet another project?

### ISSUE THREAD

**Issue by bitsofinfo** [logstash-plugins/logstash-filter-cipher#1]
Here is one I submitted last summer which has still to be evaluated/merged. 

https://github.com/elasticsearch/logstash-contrib/pull/79

**Comment by jsvd** [comment]
hey @bitsofinfo, sorry that this pr has been neglected for so long..would you mind applying it to this repo and assigning it to me? I'll do a review asap so that we can set it up for merging.

**Comment by bitsofinfo** [comment]
@jsvd is that necessary? According to Jordon's comment @ https://github.com/elasticsearch/logstash-contrib/pull/79 it sounds like it could just be merged from the old contrib project. I was looking at the code diffs last night and its looks like this new logstash-filter-cipher code is a straight copy from the contrib project.

**Comment by jsvd** [comment]
Indeed it can, I was just going to suggest first some minor cleanups regarding spacing in that PR, since it seems to have tabs in there, that misalign all the code (examples [here](https://github.com/elasticsearch/logstash-contrib/pull/79/files#diff-8046de15c827a600856f2cdb65db73edR191), [here](https://github.com/elasticsearch/logstash-contrib/pull/79/files#diff-8046de15c827a600856f2cdb65db73edR201) and [here](https://github.com/elasticsearch/logstash-contrib/pull/79/files#diff-8046de15c827a600856f2cdb65db73edR229)).

Also having just  `if @iv_random_length` instead of `if !@iv_random_length.nil?` is, for most cases, equivalent and would simplify the code a lot since there are many checks like this in the code.

That aside, the PR looks good and we're good to merge.

**Comment by jsvd** [comment]
I'll move the PR here so we can iterate on it.

**Comment by bitsofinfo** [comment]
Please do, then I'll fork it again and fix whatever is required. Thanks

**Comment by jsvd** [comment]
@bitsofinfo done

**Comment by bitsofinfo** [comment]
thanks, I'll hopefully be able to get to this, this week

**Comment by bitsofinfo** [comment]
This pull request now incorporates all the changes https://github.com/logstash-plugins/logstash-filter-cipher/pull/3

**Comment by tkocheran-chromeriver** [comment]
I'm also waiting on this pull request. A static IV is a big no-no for encryption.

**Comment by bitsofinfo** [comment]
All relevant stuff is in referenced PRs above
