### ISSUE TITLE
base64 seems to not work even when enabled

### ISSUE THREAD

**Issue by focusaurus** [logstash-plugins/logstash-filter-cipher#6]
I'm running version 0.1.5 of this filter. Here's my filter spec:

```
cipher {
  algorithm => "aes-256-cbc"
  # base64 seems to not actually work
  base64 => true
  mode => "encrypt"
  key => "redacted"
  iv => "redacted"
  source => "some_secret_plaintext"
  target => "some_secret_ciphertext"
  remove_field => ["message", "some_secret_plaintext"]
}
```

But the "some_secret_ciphertext" comes out in straight binary:

```
"some_secret_ciphertext":"PUÌþö#·\u000Fø%¹\f¸\u001Dt "
```

Consistently reproducible for me. I looked briefly at the code and at a glance it seemed like it should work. Not sure what's going wrong.

**Comment by wiibaa** [comment]
Just by reading the code I think you are right.
it seems that [line 106](https://github.com/logstash-plugins/logstash-filter-cipher/blob/master/lib/logstash/filters/cipher.rb#L106) is an exact copy-paste of [line 102](https://github.com/logstash-plugins/logstash-filter-cipher/blob/master/lib/logstash/filters/cipher.rb#L102) but should be replaced to work on the `result` variable instead of the `data` variable
`result =  Base64.encode64(result) if @base64 == true`
Can you please try this ?

**Comment by bitsofinfo** [comment]
Pretty sure fix for this and other things have been sitting in this PR forever, prior to this new repo

https://github.com/logstash-plugins/logstash-filter-cipher/pull/3

Been using this patch in prod for over a year, works fine

**Comment by bitsofinfo** [comment]
Original fix @ https://github.com/logstash-plugins/logstash-filter-cipher/commit/10f3e2366fd939e8c7c9e548db5854da5f49013c

**Comment by focusaurus** [comment]
@bitsofinfo I confirmed using the patched version from #3 works well for me. Would love to see that merged and a new release published.

**Comment by bitsofinfo** [comment]
Cool, glad it worked, please comment on #3 maybe it will get moving :)

**Comment by bitsofinfo** [comment]
@focusaurus I also recommend you don't use the static IV, if you are using the patch, be sure to use the random IV functionality.

**Comment by ubiquitousthey** [comment]
Added PR #7 to fix base64 issue

**Comment by jsvd** [comment]
closing since pr #3 has been merged
